import {DEFAULT} from './viewModeTypes';
import {IDLE} from './playerStatusTypes';
import {randomId} from './helpers';
export default function({user, deb, i18n, router, ssr, locales}) {
    return {
        ssr,
        inited: false,
        windowWidth: 0,
        name: null,
        controls: true,
        progress: 0,
        features: {
            p2pProgress: true,
            title: true,
            settings: true,
            fullscreen: true,
            subtitles: true,
            continue: true,
            playpause: true,
            currentTime: true,
            timeline: true,
            duration: true,
            volume: true,
            chromecast: true,
            browse: true,
            download: true,
            captions: true,
            embed: true,
            autoSubtitles: true,
        },
        isCached: false,
        lastTime: null,
        zipDownload: false,
        adsInjected: false,
        completedPieces: [],
        width: null,
        height: null,
        imdbId: null,
        autoplay: false,
        firstPlay: true,
        playerControlsShown: true,
        playerFullScreen: false,
        playerNativeFullScreen: false,
        caption: null,
        captionSize: 0,
        externalSubtitles: [],
        externalPoster: '',
        externalTitle: null,
        header: true,
        adblock: false,
        apiUnreachable: false,
        viewMode: DEFAULT,
        theme: null,
        user,
        version: VERSION,
        subtitle: null,
        time: 0,
        mediaInfo: null,
        debug: deb,
        baseURL: 'https://webtor.io',
        sponsorURL: 'https://www.patreon.com/bePatron?u=24145874',
        authURL: '/auth/patreon',
        userID: randomId(),
        downloadID: null,
        torrent: null,
        file: null,
        downloadPath: null,
        pwd: '/',
        fileHistory: null,
        playerStatus: IDLE,
        playerFilePath: null,
        playerSourceUrl: null,
        wrongFormat: false,
        deliveryFailure: false,
        loadState: false,
        deliveryToken: null,
        abused: false,
        stats: {},
        errors: {},
        source: [],
        loadError: false,
        lang: i18n.locale,
        userLang: locales.length > 0 && locales[0].normalized ? locales[0].normalized : i18n.fallbackLocale,
        fallbackLang: i18n.fallbackLocale,
        currentDirFileState: {},
        recentTorrents: {},
        newPosition: null,
        seeder: null,
        attachedTracks: [],
        downloadStats: {},
        downloadType: null,
    };
};